"""empty message

Revision ID: 4b783bcaba87
Revises: a79a697b53ad
Create Date: 2020-04-09 14:44:18.115115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b783bcaba87'
down_revision = 'a79a697b53ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digitalcontent', sa.Column('product_variant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'digitalcontent', 'productvariant', ['product_variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'digitalcontent', type_='foreignkey')
    op.drop_column('digitalcontent', 'product_variant_id')
    # ### end Alembic commands ###
