"""empty message

Revision ID: 97ed1251663a
Revises: a32069eb3f3c
Create Date: 2020-04-04 12:44:40.289088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ed1251663a'
down_revision = 'a32069eb3f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
