"""Added Shop/Product models n

Revision ID: a22324581a55
Revises: d6adcf4cab43
Create Date: 2020-04-04 14:14:05.978991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22324581a55'
down_revision = 'd6adcf4cab43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('seo_title', sa.String(length=100), nullable=True),
    sa.Column('seo_description', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('background_image', sa.LargeBinary(), nullable=True),
    sa.Column('background_image_alt', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('seo_title', sa.String(length=100), nullable=True),
    sa.Column('seo_description', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('background_image', sa.LargeBinary(), nullable=True),
    sa.Column('background_image_alt', sa.String(length=128), nullable=True),
    sa.Column('minimun_price_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producttype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('has_variants', sa.Boolean(), nullable=True),
    sa.Column('is_shipping_required', sa.Boolean(), nullable=True),
    sa.Column('is_digital', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('seo_title', sa.String(length=100), nullable=True),
    sa.Column('seo_description', sa.String(length=100), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('price_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['producttype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('producttype')
    op.drop_table('category')
    op.drop_table('brand')
    # ### end Alembic commands ###
