"""Aadded Attributes

Revision ID: a2d96de86527
Revises: 4b783bcaba87
Create Date: 2020-04-09 22:10:45.291135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d96de86527'
down_revision = '4b783bcaba87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productattribute',
    sa.Column('seo_title', sa.String(length=100), nullable=True),
    sa.Column('seo_description', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['producttype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productrecommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productattributevalue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['productattribute.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('producttype', sa.Column('seo_description', sa.String(length=100), nullable=True))
    op.add_column('producttype', sa.Column('seo_title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producttype', 'seo_title')
    op.drop_column('producttype', 'seo_description')
    op.drop_table('productattributevalue')
    op.drop_table('productrecommendation')
    op.drop_table('productattribute')
    # ### end Alembic commands ###
