"""empty message

Revision ID: cce0a38ed48b
Revises: a22324581a55
Create Date: 2020-04-09 14:32:12.570944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce0a38ed48b'
down_revision = 'a22324581a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
