"""Starting well again

Revision ID: d6adcf4cab43
Revises: e817e42fe31c
Create Date: 2020-04-04 13:02:31.274515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6adcf4cab43'
down_revision = 'e817e42fe31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
