"""Starting well

Revision ID: e817e42fe31c
Revises: 97ed1251663a
Create Date: 2020-04-04 13:01:57.027104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e817e42fe31c'
down_revision = '97ed1251663a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
